meta_product_name: "Nouyuu"
meta_title: "Nouyuu - Helping you successfully grow your crops"
meta_description: "Helpful and informative gardening app"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@nouyuu"   # required for Twitter Cards
